DROP DATABASE IF EXISTS foodDB;
CREATE DATABASE foodDB;

USE foodDB;

DROP TABLE IF EXISTS food;
CREATE TABLE food (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR (255) NOT NULL,
  price INT NOT NULL,
  rating INT NOT NULL
);